apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: aiq75cq35-nodejs 
  janus-idp.io/tekton: aiq75cq35-nodejs
  backstage.io/kubernetes-id: aiq75cq35-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aiq75cq35-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml