apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aiq75cq35-nodejs
  janus-idp.io/tekton: aiq75cq35-nodejs
  backstage.io/kubernetes-id: aiq75cq35-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aiq75cq35-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
